
[Network]
#type rpc or channel
CAFile="ca.crt"
CertFile="sdk.crt"
KeyFile="sdk.key"
# if the certificate context is not empty, use it, otherwise read from the certificate file
# multi lines use triple quotes
CAContext=''''''
KeyContext=''''''
CertContext=''''''
# list of node address, ipv4/ipv6/domain
NodesURL=["127.0.0.1:20200",]

[Account]
# only support PEM format for now, if the certificate context is not empty, use it, otherwise read from the certificate file
PrivateKeyFile=".ci/0x83309d045a19c44dc3722d15a6abd472f95866ac.pem"
PrivateKeyContext=''''''

[Chain]
Group="group0"
SMCrypto=false

[log]
Path="./"
